version: '3.8'

services:
  EmployeesService:
    image: EmployeesService
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    # environment:
    #   - ConnectionStrings__DefaultConnection=Server=(localdb)\\Servidor;Database=TestCompany;Trusted_Connection=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      # SA_PASSWORD: "TuPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"